/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import PropTypes from 'prop-types'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

// https://threejs.org/docs/#api/en/objects/Group
export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/models/f3f13.glb')
  return (
    <group ref={group} {...props}  dispose={null}>
      <mesh material={materials.palette} geometry={nodes.mesh_0.geometry} />
    </group>
  )
}

Model.propTypes = {
  position: PropTypes.array,
  rotation: PropTypes.array,
  scale: PropTypes.array,
}

Model.defaultProps = {
  position: [0, -10, 0],
  rotation: [0, 0, 0],
  scale: [1, 1, 1]
}
